// admin/src/app/components/courses/courses.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Select } from 'primeng/select';
import { ButtonModule } from 'primeng/button';
import { InputIcon } from 'primeng/inputicon';
import { IconField } from 'primeng/iconfield';
import { InputTextModule } from 'primeng/inputtext';
import { Router } from '@angular/router';
import { CoursesApiService } from '../../services/courses-api.service';
import { CommonModule } from '@angular/common';
import { MessageService } from 'primeng/api';
import { Toast } from 'primeng/toast';
import { OverviewApiService } from '../../services/overview-api.service';
import { filter } from 'rxjs';

interface Major {
  name: string;
  code: string;
}

@Component({
  selector: 'app-courses',
  imports: [
    FormsModule,
    Select,
    ButtonModule,
    InputIcon,
    IconField,
    InputTextModule,
    CommonModule,
    Toast
  ],
  templateUrl: './courses.component.html',
  styleUrl: './courses.component.scss',
  providers: [MessageService],
})
export class CoursesComponent {
  courses: any[] = [];
  majors: Major[] | undefined;
  filteredCourses: any[] = [];
  selectedMajor: Major | undefined;

  constructor(
    private router: Router,
    private CoursesAPI: CoursesApiService,
    private messageService: MessageService,
    private overviewAPI: OverviewApiService
  ) {}

  ngOnInit() {
    this.overviewAPI.getMajors().subscribe({
      next: (data) => {
          // console.log('get majors data', data);
          this.majors = data.map((major: any) => ({
              name: major.major_name.split("-").join(" "),
              code: major.major_name
          }));
          this.majors?.unshift({ name: 'All', code: 'all' });
      },
      error: (err) => {
          console.error('get majors error', err);
      }
    });

    this.CoursesAPI.getCourses().subscribe({
      next: (data) => {
        // console.log('get courses data', data);
        this.courses = data;
        this.filteredCourses = data;
      },
      error: (err) => console.error('get courses error', err)
    });
  }

  goToEditor() {
    this.router.navigate(['/editor']);
  }

  deleteCourse(courseID: number) {
    this.CoursesAPI.deleteCourse(courseID).subscribe({
      next: (data) => {
        // console.log('delete course data', data);
        this.courses = this.courses.filter(course => course.id !== courseID);
        this.filteredCourses = this.courses;
        this.selectedMajor = undefined;
        this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Course deleted successfully' });
      },
      error: (err) => {
        this.messageService.add({ severity: 'success', summary: 'Success', detail: 'Something wrong, try again' });
        console.error('delete course error', err);
      }
    });
  }

  selectMajor(){
    console.log('selected major', this.selectedMajor);
    if(this.selectedMajor){
      if(this.selectedMajor.code === 'all'){
        this.filteredCourses = this.courses;
        return;
      }
      let filteredCourses = this.courses;
      this.filteredCourses = filteredCourses.filter(course => course.course_major.split(", ").includes(this.selectedMajor?.code));
    }
  }

}

<div class="p-6 overflow-auto h-[100vh]">
    <p-toast />
    <div class="mb-6 flex justify-between items-center">
        <div>
            <h1 class="text-2xl font-bold text-gray-800">Courses</h1>
            <p class="text-gray-500">Welcome back</p>
        </div>
    </div>

    <div class="bg-white p-6 mb-[30px] rounded-xl shadow-sm w-full flex flex-wrap justify-between items-center gap-4">
        <div class="flex flex-wrap gap-4">
            <p-iconfield>
                <p-inputicon styleClass="pi pi-search" />
                <input type="text" pInputText placeholder="Search..." />
            </p-iconfield>
            <p-select [options]="majors" [(ngModel)]="selectedMajor" (ngModelChange)="selectMajor()" optionLabel="name" placeholder="Select Major" class="w-full md:w-56" />
        </div>
        <p-button (click)="goToEditor()" label="Add Course" icon="pi pi-plus" />
    </div>

    <div class="flex flex-wrap gap-6">
        <div *ngFor="let course of filteredCourses" class="bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow overflow-auto h-fit w-[360px]">
            <img
                src={{course.course_image}}
                alt="Course Image"
                width={360}
                height={200}
                class="w-full h-[200px] object-cover rounded-t-xl"
            />
            <div class="p-5 min-h-[165px] relative pb-[60px]">
                <h3 class="text-lg font-semibold text-gray-800 mb-2">
                    {{course.course_name}}
                </h3>
                <p class="text-gray-600 mb-[10px] text-sm">
                    {{course.course_description}}
                </p>
                <div class="flex flex-wrap gap-2">
                    <p *ngFor="let major of course.course_major.split(', ')" class="text-[11px] font-medium text-[#6366f1] bg-[#6366f12e] px-[9px] py-[5px] rounded-full">{{major.split("-").join(" ")}}</p>
                    <!-- <p class="text-[11px] font-medium text-[#6366f1] bg-[#6366f12e] px-[9px] py-[5px] rounded-full">{{course.course_major}}</p> -->
                </div>
                <div class="absolute flex bottom-[11px] left-[18px] w-[90%] flex-wrap justify-center gap-2">
                    <button 
                        class="px-[30px] py-[9px] rounded-[4px] bg-[#6665f1] text-white font-medium text-sm flex items-center transition-all duration-300 cursor-pointer hover:bg-[#4543b9]"
                    >
                        View
                    </button>
                    <button 
                        class="px-[30px] py-[9px] rounded-[4px] bg-[#ea1212] text-white font-medium text-sm flex items-center transition-all duration-300 cursor-pointer hover:bg-[#a42424]"
                        (click)="deleteCourse(course.id)"
                    >
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

// client/app/home/Courses.tsx
"use client"
import { ChevronRight } from 'lucide-react'
import useAuthStore from '../store/authStore'
import { useQuery, useQueryClient } from 'react-query';
import Image from 'next/image';
import { message } from 'antd';
import Link from 'next/link';

const Courses = () => {
    const queryClient = useQueryClient();
    const userData = useAuthStore((state => state.userData));

    const {data:courses, isLoading, error} = useQuery({
        queryKey: ['courses'],
        queryFn: () => fetch(`${process.env.NEXT_PUBLIC_API_URL}/course/coursesList`,{
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("token")}`,
                },
            })
            .then(res => res.json()),
        enabled: !!userData
    })

    console.log(courses);

    const handleEnrollCourse = async(courseID:number) => {
        try {
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/course/enrollCourse?courseID=${courseID}`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("token")}`,
                }
            });
            const data = await res.json();
            if (res.ok) {
                // message.success("Successfully enrolled in course!");
                queryClient.invalidateQueries({ queryKey: ['courses'] });
                queryClient.invalidateQueries({ queryKey: ['myCourses'] });
            } else {
                console.error("Failed to enroll in course:", data);
            }
        } catch(error) {
            console.error("Error enrolling in course:", error);
        }
    }

    return (
        <div className="h-[calc(100vh-74px)] overflow-auto">
            {/* Page Title */}
            <div className="px-8 pt-8 pb-4">
                <h1 className="text-2xl font-bold text-gray-800">Welcome Back {userData?.username}</h1>
                <p className="text-gray-500 mt-1">
                    Good to see you! Let’s study.
                </p>
            </div>
            {/* Content Grid */}
            <div className="flex flex-wrap p-8 gap-6">
                {isLoading && <div className="text-center text-gray-500">Loading...</div>}
                {error && <div className="text-center text-red-500">Error loading courses</div>}
                {courses?.myCourses && courses?.myCourses?.map((course: any, idx: number) => (
                    <div 
                        className="bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow overflow-auto h-auto w-[360px]"
                        key={idx}
                    >
                        <Image
                            src={course?.course_image}
                            alt="Course Image"
                            width={360}
                            height={200}
                            className="w-full h-[200px] object-cover rounded-t-xl"
                        />
                        <div className="p-5 min-h-[165px] relative pb-[70px]">
                            <h3 className="text-lg font-semibold text-gray-800 mb-2">
                                {course?.course_name}
                            </h3>
                            <p className="text-gray-600 text-sm">
                                {course?.course_description}
                            </p>
                            <div className="absolute bottom-[10px] left-[18px] w-[90%] flex-wrap">
                                <div className='w-full flex justify-between items-center'>
                                    <span className="text-xs font-medium text-amber-600 bg-amber-50 px-2 py-1 rounded-full">
                                        {course?.status}
                                    </span>
                                    <Link href={`/home/course-${course?.course_name.split(" ").join("-").toLowerCase()}-${course?.course_id}`} className="text-indigo-600 hover:text-indigo-700 font-medium text-sm flex items-center cursor-pointer">
                                        {
                                            course?.status === 'completed' ? 'View' : 'Continue'
                                        }
                                        <ChevronRight size={16} className="ml-1" />
                                    </Link>
                                </div>
                                <div className="flex items-center mt-[8px]">
                                    <div className="flex-1 bg-gray-200 h-2 rounded-full overflow-hidden">
                                        <div className="bg-indigo-500 h-full rounded-full" style={{ width: `${course?.progress}%` }}></div>
                                    </div>
                                    <span className="text-xs text-gray-500 ml-2">{course?.progress}%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                ))}
                {courses?.courses && courses?.courses?.map((course: any, idx: number) => (
                    <div 
                        className="bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow overflow-auto w-[360px] h-auto"
                        key={idx}
                    >
                        <Image
                            src={course?.course_image}
                            alt="Course Image"
                            width={360}
                            height={200}
                            className="w-full h-[200px] object-cover rounded-t-xl"
                        />
                        <div className="p-5 min-h-[165px] relative pb-[60px]">
                            <h3 className="text-lg font-semibold text-gray-800 mb-2">
                                {course?.course_name}
                            </h3>
                            <p className="text-gray-600 text-sm">
                                {course?.course_description}
                            </p>
                            <div className="flex justify-center items-center absolute bottom-[10px] left-[18px] w-[90%]">
                                <button 
                                    className="px-[30px] py-[9px] rounded-[4px] bg-[#6665f1] text-white font-medium text-sm flex items-center transition-all duration-2000"
                                    onClick={() => handleEnrollCourse(course?.id)}
                                >
                                    Start
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    )
}

export default Courses
